with-expecter: true
issue-845-fix: true
disable-version-string: true
resolve-type-alias: false
packages:
  github.com/raythx98/gohelpme/tool/jwthelper:
    interfaces:
      IJwt:
  github.com/raythx98/gohelpme/tool/logger:
    interfaces:
      ILogger: